### PR TITLE
sudoers.d. changed executable file list to .d folder

### PR DESCRIPTION
**Pull request by edospadoni**
NethServer/dev#5118

### CODE REVIEW

**Comment by filippocarletti** [comment]
Do we need to expand sudoers.conf in the -update event?

**Review by gsanchietti — CHANGES_REQUESTED** [review]
Please also remove the expansion of /etc/sudoers file from the createlinks script.

**Comment by DavidePrincipi** [comment]
@edospadoni we need also special permissions on the sudoers.d configuration. See for instance

https://github.com/NethServer/nethserver-dc/blob/44e621217cc6abf7fcb196dd7e89be24a89ac749/nethserver-dc.spec#L58

**Review by DavidePrincipi — APPROVED** [review]
Please, in the future avoid whitespace changes on code sections that are not related with the current patch.

**Review by gsanchietti — APPROVED** [review]

**Pull request merged**
